name: sporting_club
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.53+53

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  flutter_cupertino_localizations: ^1.0.1

  http: ^0.13.4
#  provider: ^4.1.1
  provider: ^6.0.2

  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.8
#  connectivity: ^3.0.6
  connectivity_plus: ^2.2.0
  firebase_core: ^1.13.1
#  firebase_database: ^9.0.8
#  cupertino_icons: ^0.1.2

  carousel_slider: ^4.0.0
  url_launcher: ^6.0.18
#  get_version: ^0.2.0+1
  cached_network_image: ^3.2.0
  dio: ^4.0.4
  image_picker: ^0.8.4+7
  path_provider: ^2.0.8
  path: ^1.8.0
  intl: ^0.17.0
  firebase_crashlytics: ^2.5.3
  firebase_auth: ^3.3.9
  firebase_messaging: ^11.2.8
#  slide_popup_dialog:
  modal_bottom_sheet: ^2.0.0
  modal_progress_hud_nsn:
  page_view_indicators: ^2.0.0
  flutter_tags: ^1.0.0-nullsafety.1
  sliding_up_panel: ^2.0.0+1
  month_picker_dialog: ^0.4.0

  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0
  share: ^2.0.4
#  flutter_branch_io_plugin: ^1.0.1+1
  firebase_analytics:
#  flutter_webview_plugin:
#    git: https://github.com/youssefali424/flutter_webview_plugin

  flutter_native_image: ^0.0.6+1
  flutter_email_sender: ^5.0.2
#  flutter_crashlytics:
  package_info: ^2.0.2
  flutter_slidable: ^1.2.0
  flutter_widget_from_html: ^0.8.5
  flutter_branch_sdk: ^4.0.0
#  uni_links: ^0.4.0
  #  path: ^1.6.2
  photo_view: ^0.13.0
  clippy_flutter: ^2.0.0-nullsafety.1
#  pin_entry_text_field: 0.1.4
  pin_code_fields: ^7.3.0
  persian_number_utility: ^1.1.1
  open_file: ^3.2.1
#  qr_flutter:
  pdf: ^3.7.1
  zoom_widget: ^0.2.1


  barcode_widget: ^2.0.2
#  custom_map_markers:
  flutter_animarker:
  maps_toolkit: ^2.0.0
  location: ^4.3.0
  # flutter_callkit_incoming: ^1.0.2+1
#  android_alarm_manager_plus: ^2.0.6+1
#  flutter_ringtone_player: ^3.2.0
  # awesome_notifications: ^0.6.21
#  just_audio: ^0.9.29
  permission_handler: ^10.1.0
  onesignal_flutter: ^3.4.1
  webview_flutter: ^3.0.4
  flutter_riverpod:
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
#  jiffy: ^2.2.0
#  cached_network_image: ^2.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bahij
      fonts:
        - asset: fonts/Bahij-Plain.ttf
          weight: 500

        - asset: fonts/Bahij-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
